export enum Category {
  Groceries = 1,
  Bakery,
  Restaurant,
  Bar,
  Cafe,
  Hotel,
  ATM,
  ShoppingFashion,
  BeautyWellness,
  Electronics,
  SportFitness,
  Entertainment,
  ServicesMedical,
  Other,
}

export const categoryNames: Record<Category, string> = {
  [Category.Groceries]: "Groceries",
  [Category.Bakery]: "Bakery",
  [Category.Restaurant]: "Restaurant",
  [Category.Bar]: "Bar",
  [Category.Cafe]: "Cafe",
  [Category.Hotel]: "Hotel",
  [Category.ATM]: "ATM / Money Changer",
  [Category.ShoppingFashion]: "Shopping / Fashion",
  [Category.Electronics]: "Electronics",
  [Category.BeautyWellness]: "Beauty & Wellness",
  [Category.SportFitness]: "Sport & Fitness",
  [Category.Entertainment]: "Entertainment",
  [Category.ServicesMedical]: "Services / Medical",
  [Category.Other]: "Other",
}

export const categoryIcons: Record<Category, string> = {
  [Category.Groceries]: "local-grocery-store",
  [Category.Restaurant]: "restaurant",
  [Category.Bar]: "liquor",
  [Category.Cafe]: "local-cafe",
  [Category.Bakery]: "bakery-dining",
  [Category.Hotel]: "hotel",
  [Category.ShoppingFashion]: "storefront",
  [Category.BeautyWellness]: "spa",
  [Category.Electronics]: "smartphone",
  [Category.SportFitness]: "sports",
  [Category.Entertainment]: "stadium",
  [Category.ServicesMedical]: "medical-services",
  [Category.ATM]: "local-atm",
  [Category.Other]: "more-horiz",
}

/* eslint-disable camelcase */
export const categories: Record<string, Category> = {
  "local-grocery-store": Category.Groceries,
  "bakery-dining": Category.Bakery,
  "tapas": Category.Restaurant,
  "wine-bar": Category.Bar,
  "liquor": Category.Bar,
  "restaurant": Category.Restaurant,
  "lunch-dining": Category.Restaurant,
  "emoji-food-beverage": Category.Cafe,
  "local-cafe": Category.Cafe,
  "cake": Category.Bakery,
  "icecream": Category.Cafe,
  "sports-bar": Category.Bar,

  "hotel": Category.Hotel,
  "chalet": Category.Hotel,
  "camping": Category.Hotel,
  "cottage": Category.Hotel,

  "local-atm": Category.ATM,
  "currency-exchange": Category.ATM,
  "attach-money": Category.ATM,
  "account-balance": Category.ATM,

  "storefront": Category.ShoppingFashion,
  "card-giftcard": Category.ShoppingFashion,
  "chair": Category.ShoppingFashion,
  "luggage": Category.ShoppingFashion,
  "diamond": Category.ShoppingFashion,
  "local-florist": Category.ShoppingFashion,
  "photo-camera": Category.ShoppingFashion,
  "toys": Category.ShoppingFashion,
  "games": Category.ShoppingFashion,
  "watch": Category.ShoppingFashion,
  "smartphone": Category.Electronics,
  "hardware": Category.Electronics,
  "videogame-asset": Category.Electronics,
  "local-mall": Category.ShoppingFashion,
  "checkroom": Category.ShoppingFashion,
  "vaping-rooms": Category.ShoppingFashion,
  "smoking-rooms": Category.ShoppingFashion,
  "grass": Category.ShoppingFashion,
  "edit": Category.ShoppingFashion,
  "videcam": Category.Electronics,

  "content-cut": Category.BeautyWellness,
  "spa": Category.BeautyWellness,
  "sauna": Category.BeautyWellness,
  "visibility": Category.BeautyWellness,

  "fitness-center": Category.SportFitness,
  "sports": Category.SportFitness,
  "sports-martial-arts": Category.SportFitness,
  "sports-hockey": Category.SportFitness,
  "sports-soccer": Category.SportFitness,
  "pedal-bike": Category.SportFitness,

  "nightlife": Category.Entertainment,
  "mic": Category.Entertainment,
  "celebration": Category.Entertainment,
  "casino": Category.Entertainment,
  "stadium": Category.Entertainment,
  "local-movies": Category.Entertainment,
  "music-note": Category.Entertainment,
  "museum": Category.Entertainment,
  "park": Category.Entertainment,
  "beach-access": Category.Entertainment,
  "golf-course": Category.Entertainment,
  "nature-people": Category.Entertainment,
  "attractions": Category.Entertainment,
  "scuba-diving": Category.Entertainment,
  "kayaking": Category.Entertainment,
  "surfing": Category.Entertainment,
  "sailing": Category.Entertainment,
  "castle": Category.Entertainment,
  "palette": Category.Entertainment,
  "piano": Category.Entertainment,
  "raven": Category.Entertainment,
  "bedroom-baby": Category.Entertainment,
  "sports-score": Category.Entertainment,

  "medical-services": Category.ServicesMedical,
  "local-pharmacy": Category.ServicesMedical,
  "local-hospital": Category.ServicesMedical,
  "dentistry": Category.ServicesMedical,
  "surgical": Category.ServicesMedical,

  "construction": Category.ServicesMedical,
  "roofing": Category.ServicesMedical,
  "factory": Category.ServicesMedical,
  "imagesearch-roller": Category.ServicesMedical,
  "grid-view": Category.ServicesMedical,
  "carpenter": Category.ServicesMedical,
  "build": Category.ServicesMedical,
  "window": Category.ServicesMedical,
  "agriculture": Category.ServicesMedical,
  "potted-plant": Category.ServicesMedical,
  "hive": Category.ServicesMedical,
  "footprint": Category.ServicesMedical,
  "architecture": Category.ServicesMedical,
  "plumbing": Category.ServicesMedical,
  "electric-bolt": Category.ServicesMedical,
  "hvac": Category.ServicesMedical,

  "cleaning-services": Category.ServicesMedical,
  "local-laundry-service": Category.ServicesMedical,
  "local-printshop": Category.ServicesMedical,
  "balance": Category.ServicesMedical,
  "engineering": Category.ServicesMedical,
  "computer": Category.ServicesMedical,
  "design-services": Category.ServicesMedical,
  "translate": Category.ServicesMedical,
  "science": Category.ServicesMedical,
  "lock": Category.ServicesMedical,
  "mail": Category.ServicesMedical,
  "newspaper": Category.ServicesMedical,
  "cell-tower": Category.ServicesMedical,
  "public": Category.ServicesMedical,
  "tour": Category.ServicesMedical,

  "question-mark": Category.ServicesMedical, // fallback or unknown
}
